# Basic configuration
domain: https://davidjbrossard.github.io/pdp-demo/domain_tutorial.yaml
domainRefreshInterval: 5 seconds
reportUnhealthyOnDomainRefreshError: true
failOnDeclaredAttributeNotProvided: false
license: ./conf/axiomatics_PDP.license

authentication:
  type: Basic
  user:
    username: ${ADS_USER:-ads-user}
    hashPassword: ${ADS_PASSWORD}

## Dropwizard part of configuration. See http://www.dropwizard.io/1.3.5/docs/manual/configuration.html
server:
  applicationConnectors:
  - type: http
    port: ${ADS_AUTHZ_PORT:-8380}
  adminConnectors:
  - type: http
    port: ${ADS_ADMIN_PORT:-8381}

audit:
  mode: verbose

# https://www.dropwizard.io/en/latest/manual/core.html#logging
logging:
  level: INFO
  loggers:
    "com.axiomatics.audit.ads.admin":
      level: INFO
      additive: false
      appenders:
        - type: file
          layout:
            #type: json
          threshold: INFO
          # uncomment to remove log level, timestamp and class name
          # logFormat: "%m%n"
          currentLogFilename: logs/ads-admin-event.log
          archivedLogFilenamePattern: logs/ads-admin-event-%d{yyyy-MM-dd}-%i.log.gz
          archivedFileCount: 7
          timeZone: system
          maxFileSize: 10MB
    "com.axiomatics.audit.ads.eval":
      level: INFO
      additive: false
      appenders:
        - type: file
          layout:
            #type: json
          threshold: INFO
          # uncomment to remove log level, timestamp and class name
          # logFormat: "%m%n"
          currentLogFilename: logs/ads-eval-event.xml
          archivedLogFilenamePattern: logs/ads-eval-event-%d{yyyy-MM-dd}-%i.log.gz
          archivedFileCount: 7
          timeZone: system
          maxFileSize: 10MB
    "com.axiomatics.ads.core.evaluator.EvaluatorService": OFF
    "com.axiomatics": INFO
    "com.axiomatics.delegent.pipcache.jcs": OFF
    #"com.axiomatics.delegent": TRACE
    #"com.axiomatics.attributeconnector.ldap": DEBUG
    #"com.axiomatics.attributeconnector.jdbc": DEBUG
    "com.axiomatics.attributeconnector.table": WARN
  appenders:
  - type: console
    target: stdout
    timeZone: system
    #layout:
    #  type: json
    #  prettyPrint: true
    #logFormat: "%m%n"
