name: Convert ALFA to XACML
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run ALFAC Compiler
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
  
      - run: java -jar "bin/alfac.jar" "./alfa" -o ./xacml 
      - run: bin/domtool-0.9.0/bin/domtool domain --identity=demo --main-policy-id=http://axiomatics.com/alfa/identifier/demo.allowAll --attributes=./config/attributes.yaml  -o ./domain_tutorial.yaml --xacml-specifications ./xacml 
